# Setup ssh args so that ansible can connect to the k8s instances in the private subnet through bastion.
# This file will be created from the terraform apply command.
# It will look something like this.

ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -q <username@public_ip_address_of_bastion>"'
