# Tasks for initial configuration of system required for kubernetes.

- name: Remove swap entry from /etc/fstab
  ansible.posix.mount:
    backup: yes
    opts: sw
    fstype: swap
    path: none
    state: absent
  register: remove_swap_entry

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: remove_swap_entry is changed

- name: Loading br_netfilter module for iptables to see bridged traffic
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Copy kernel module configuration
  ansible.builtin.copy:
    src: kernel-module-k8s.conf
    dest: /etc/modules-load.d/
        
- name: Setting sysctl config for iptables to see bridged traffic
  ansible.posix.sysctl:
    name: "{{ item }}"
    sysctl_file: /etc/sysctl.d/60-sysctl-k8s.conf
    sysctl_set: yes
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

# Required for persistent volume using AWS EFS.
- name: Install nfs helper program
  ansible.builtin.apt:
    update_cache: yes
    name: nfs-common
    state: present

- name: Import Docker tasks
  ansible.builtin.import_tasks: docker.yml

- name: Import Kubernetes tasks
  ansible.builtin.import_tasks: k8s.yml
