- name: Disable swap
  ansible.builtin.command: swapoff -a
      
- name: Edit /etc/fstab
  ansible.builtin.command: sed -i.bkp '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      
- name: Letting iptables see bridged traffic - modprobe
  ansible.builtin.command: modprobe br_netfilter    
      
- name: Copy kernel module configuration
  ansible.builtin.copy:
    src: kernel-module-k8s.conf
    dest: /etc/modules-load.d/
        
- name: Copy sysctl configuration
  ansible.builtin.copy:
    src: 60-sysctl-k8s.conf
    dest: /etc/sysctl.d/
        
- name: Letting iptables see bridged traffic - sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/60-sysctl-k8s.conf
