# Installation:
# ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
  - name: community.general

roles:
  - name: elastic.elasticsearch
    version: v7.15.1
  - name: geerlingguy.kibana
    version: 4.0.1
