- name: common steps for k8s cluster
  hosts: k8s # master and worker nodes
  become: yes
  roles:
    - common-k8s
  tags:
    - setup-k8s

- name: setup k8s master
  hosts: master
  become: yes
  roles:
    - k8s-master
  tags:
    - setup-k8s

- name: setup k8s worker
  hosts: worker
  become: yes
  roles:
    - k8s-worker
  tags:
    - setup-k8s

- name: deploy owncloud
  hosts: master
  roles:
    - owncloud
  tags:
    - deploy-app

