- name: Common steps for k8s cluster
  hosts: all # master and worker nodes
  become: yes
  roles:
    - common-k8s

- name: k8s master
  hosts: master
  become: yes
  roles:
    - k8s-master

- name: k8s worker
  hosts: worker
  become: yes
  roles:
    - k8s-worker
