- name: Create a cluster with kubeadm
  ansible.builtin.command:
    cmd: "kubeadm init --apiserver-advertise-address={{ apiserver_advertise_address }}"
    creates: /etc/kubernetes/admin.conf
  register: create_k8s_cluster

- name: Create .kube directory
  ansible.builtin.file:
    group: "{{ admin_user }}"
    owner: "{{ admin_user }}"
    path: "/home/{{ admin_user }}/.kube"
    recurse: yes
    state: directory

- name: Copy kubeconfig file
  ansible.builtin.copy:
    group: "{{ admin_user }}"
    owner: "{{ admin_user }}"
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ admin_user }}/.kube/config"
    backup: yes

- name: Deploy pod network
  ansible.builtin.shell:
    cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  become_user: "{{ admin_user }}"
  when: create_k8s_cluster is changed

- name: Remove taint to schedule pods on master
  ansible.builtin.command:
    cmd: kubectl taint nodes --all node-role.kubernetes.io/master-
  become_user: "{{ admin_user }}"
  when: create_k8s_cluster is changed

- name: Get the join command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: k8s_join_command
  when: create_k8s_cluster is changed

- name: Store the join command locally
  ansible.builtin.copy:
    content: "{{ k8s_join_command.stdout }}"
    dest: ./k8s_join_script.sh
  delegate_to: 127.0.0.1
  when: create_k8s_cluster is changed
