apiVersion: v1
kind: Service
metadata:
  name: owncloud-service
  namespace: owncloud-namespace
spec:
  selector:
    app: owncloud
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000

