# Tasks for installing and configuring nginx.

- name: Install nginx dependencies
  ansible.builtin.apt:
    update_cache: yes
    name: ["curl", "gnupg2", "ca-certificates", "lsb-release", "ubuntu-keyring"]
    state: present

- name: Add nginx's GPG key
  ansible.builtin.shell:
    cmd:  curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
    creates: /usr/share/keyrings/nginx-archive-keyring.gpg
    
- name: Setup nginx's repository
  ansible.builtin.apt_repository:
    filename: nginx
    repo: deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx
    state: present

- name: Install nginx
  ansible.builtin.apt:
    name: "{{ nginx_package }}"
    state: present
  register: install_nginx

- name: Copy nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    backup: yes

- name: Copy virtual host config
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
    backup: yes
  when: install_nginx is changed

- name: Start nginx
  ansible.builtin.systemd:
    enabled: yes
    name: nginx
    state: started

- name: Import Kibana SSL setup tasks
  ansible.builtin.import_tasks: kibana-ssl-setup.yml
  when: kibana_ssl_setup == true
  tags:
    - kibana-ssl-setup

