apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
  nfs:
    server: "{{ aws_efs_dns_name }}"
    path: "/"

