apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-efs-pvc
  namespace: owncloud-namespace
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

