# Tasks for installing and configuring heartbeat.

- name: Install heartbeat dependencies
  ansible.builtin.apt:
    update_cache: yes
    name: "apt-transport-https"
    state: present

- name: Add heartbeat's GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Setup heartbeat's repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ heartbeat_version }}/apt stable main"
    state: present

- name: Install heartbeat
  ansible.builtin.apt:
    name: "{{ heartbeat_package }}"
    state: present

- name: Copy heartbeat config
  ansible.builtin.template:
    src: heartbeat.yml.j2
    dest: /etc/heartbeat/heartbeat.yml

- name: Start heartbeat
  ansible.builtin.service:
    enabled: yes
    name: heartbeat-elastic
    state: started

