# Tasks for deploying owncloud application onto kubernetes cluster.

- name: Create directory for owncloud
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/owncloud/"
    state: directory

- name: Copy owncloud k8s files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/home/{{ admin_user }}/owncloud/"
  loop: ['01-namespace.yml', '02-persistent-volume.yml', '03-persistent-volume-claim.yml', '04-config-map.yml', '05-secret.yml', '06-deployment.yml', '07-service.yml']
  register: owncloud_k8s_files

- name: Deploy owncloud
  ansible.builtin.command:
    cmd: kubectl apply -f "/home/{{ admin_user }}/owncloud/"
  when: owncloud_k8s_files is changed

